version: '2'

services:
    # Laravel application
    laravel_php_fpm:
        build: ./php-fpm
        container_name: fs_laravel_php_fpm
        volumes:
            - ./laravel:/var/www/laravel
            - ./storage/app:/var/www/laravel/storage/app
            - ./storage/log:/var/www/laravel/storage/logs
        links:
            - "laravel_database"
        ports:
            - "9010:9000"
        depends_on:
            - "laravel_database"
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=laravel_database"

    # Webserver
    nginx:
        build: ./nginx
        container_name: fs_laravel_nginx
        ports:
            - "82:80"
        links:
            - laravel_php_fpm
        volumes_from:
            - laravel_php_fpm
        volumes:
            - ./logs/nginx/:/var/log/nginx
        restart: always

    # The Database
    laravel_database:
        image: mysql:latest
        container_name: fs_laravel_mysql
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
            - "./db/dbdata:/var/lib/mysql"
        environment:
            - "MYSQL_DATABASE=fellowship"
            - "MYSQL_USER=fellowship"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=root"
        ports:
            - "33063:3306"
        restart: always
